[profile.default]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "permit2/=lib/permit2/",
]
solc_version = "0.8.23"
ffi = true

[profile.ci]
libs = ["lib"]
optimizer = false
out = "out"
fuzz_runs = 5000

[profile.deploy]
optimizer = true
optimizer_runs = 10_000_000
via_ir = true
fs_permissions = [{ access = "read", path = "./out" }]

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET}" }
arbitrum = { key = "${ETHERSCAN_ARBITRUM}" }
