[profile.default]
  ffi = true
  remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "permit2/=lib/permit2/",
  ]
  solc_version = "0.8.23"

[profile.ci]
  fuzz_runs = 5000
  libs = ["lib"]
  optimizer = false
  out = "out"

[profile.deploy]
  fs_permissions = [{ access = "read", path = "./out" }]
  optimizer = true
  optimizer_runs = 10_000_000
  via_ir = true

[etherscan]
  arbitrum = { key = "${ETHERSCAN_ARBITRUM}" }
  mainnet = { key = "${ETHERSCAN_MAINNET}" }
